version: '3'
services:
    passwordapi:
        image: apernin/passwordapi-js
        ports:
            - "3000"
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - passwordapi
        ports:
            - "4000:4000"
